const express = require('express')
const router = express.Router();

const AuthRouter = require('../controller/AuthController')
// const UserRouter = require('./UserController')

const PropertyTypeRouter = require('../controller/PropertyTypeController')
const TenureTypeRouter = require('../controller/TenureTypeController')

const PropertyRouter = require('../controller/PropertyController')
const StreamRouter = require('../controller/StreamController')
const ImagesRouter = require('../controller/ImagesController')
const UploadRouter = require('../controller/UploadController')
const PropertyViewController = require('../controller/PropertyViewController')
const PropertySaveController = require('../controller/PropertySaveController')
const AgentRouter = require('../controller/AgentController')
const SellerRouter = require('../controller/SellerController')
const ChatRouter = require('../controller/ChatController')
const DeleteAccountRouter = require('../controller/DeleteAccountController')
const VerificationRouter = require('../controller/VerificationController')
const ReferralRouter = require('../controller/ReferralController')
const ModerationRouter = require('../controller/ModerationController')
const BillingRouter = require('../controller/BillingController')
const MatchRouter = require('../controller/MatchController')
const OfferRouter = require('../controller/OfferController')
const VideoRouter = require('../controller/videoController')
const BanMiddleware = require('../middleware/banMiddleware')

router.use('/webhooks', BillingRouter)
router.use('/billing', BillingRouter)
router.use(BanMiddleware)

router.use('/auth', AuthRouter)
router.use('/video', VideoRouter)
router.use('/chat', ChatRouter)
router.use('/', ChatRouter)
router.use('/offers', OfferRouter)
router.use('/', OfferRouter)
router.use('/agent', AgentRouter)
router.use('/seller', SellerRouter)
router.use('/verification', VerificationRouter)
router.use('/referral', ReferralRouter)
router.use('/moderation', ModerationRouter)
router.use('/match', MatchRouter)
router.use('/property-type', PropertyTypeRouter)
router.use('/tenure-type', TenureTypeRouter)
router.use('/property', PropertyRouter)
router.use('/property/stream', StreamRouter)
router.use('/property/images', ImagesRouter)
router.use('/property-view', PropertyViewController)
router.use('/property-save', PropertySaveController)
router.use('/delete-account', DeleteAccountRouter)
// router.use('/upload', UploadRouter)

module.exports = router;